name: Build Debian Package

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'nushell version number, i.e. 0.89.0'
        required: true
        default: '0.89.0'

jobs:
  package:
    name: debian package
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4
      with:
        ref: main
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup Nushell
      uses: hustcer/setup-nu@v3.8
      with:
        version: 0.89.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: build .deb
      id: nu
      run: nu apt/main.nu ${{ github.event.inputs.version }}

    - name: push package to packagecloud.io
      uses: computology/packagecloud-github-action@v0.8
      with:
        PACKAGE-NAME: ${{ steps.nu.outputs.archive }}
        PACKAGECLOUD-USERNAME: ${{ secrets.PKGCLOUD_USER}}
        PACKAGECLOUD-REPONAME: nushell
        PACKAGECLOUD-DISTRO: ubuntu/jammy
        PACKAGECLOUD-TOKEN: ${{ secrets.PKGCLOUD_TOKEN }}
